# Site settings
title: from scratch
email: hundredin9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write some tips and tutorials for software developers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hundredin.github.io" # the base hostname & protocol for your site
twitter_username: hundredin
github_username:  hundredin

markdown: redcarpet
highlighter: pygments
